name: Build and Test (Maven) Spring Boot Project

# When the workflow should be triggered
on:
  push:
    branches: [ main, develop ]   # Trigger on pushes to main and develop branches
  pull_request:
    branches: [ main, develop ]   # Trigger on pull requests to main and develop branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine 

    steps:
      - uses: actions/checkout@v4.1.1  # Check out your code
      
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4.1.0
      #   with:
      #     java-version: '17'  # Change Java version if required
      #     distribution: 'temurin'  # Optional: Use Temurin JDK
      #     cache: 'maven'          # Cache Maven dependencies for faster builds

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml  # Build and run tests